"""add new fields

Revision ID: 80ec3afb4cbd
Revises: 4fe3eeed9a9d
Create Date: 2025-11-08 08:07:03.968891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ec3afb4cbd'
down_revision = '4fe3eeed9a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('classname', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('realname', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'realname')
    op.drop_column('users', 'classname')
    # ### end Alembic commands ###
